### ISSUE TITLE
Experience Strategy - User Requirements

### ISSUE THREAD

**Issue by ezoehunt** [MarketplaceUX/mow#2]
Here's where we can discuss the requirements outlined in the Experience Strategy section.
Please add any of your ideas for additional functions -- things a user can do.

**Comment by flekkowich** [comment]
Hi Liz

I'm wondering if there is anyway to show a 'bigger' difference between web and app? So perhaps name of website has www.xxxx in front or there is a little www. logo somewhere? 

Also, in terms of what we are saying, should we note something about these sites? So 'these are great local mobile sites in your area' or just a 'mozilla vouched m-sites' badge? 
POV i guess, and maybe this is something we need to figure out in unity with Niran. 

(know this wasn't the question, but now I'm posing it:))
Also, viewing this I'm wondering if we need to copy google and apple in the format for 'already installed app'  It seems to me if it is already installed it shouldn't be shown / if users search for it it should be a small box (similar to website) without visual just saying 'already installed' open? Or another way to make it more clear that this is a already installed app.

**Comment by flekkowich** [comment]
[accidentally pressed enter apparently, sorry wasn't done] 

Other than that the initial layout looks great! 

From a different perspective I think it would  be great if we could think about a few KEY use cases that we want to make sure are really awesome! (and maybe we already have these). But what are the key use cases we are trying to solve? I'm happy to help brainstorm as I don't have the answer off the top of my head.

But example; i.e. for 'discovering something local' - what makes sense for that user? He/she wants great content (m.site or app), but he/she needs to distinguish between them. How do we make this as clear as possible? 
Other questions as you map out the user journey could be: What is the 'after' event, when users have visited a m.site through our homepage? Do we offer them to bookmark? Is there a 'bookmark' option next to the 'open' option? Not sure, but this would be great to think about :)

**Comment by punchyfrisky** [comment]
Hi Liz! Lots of great work here! I too would like to see more differentiation between the app and website listings - perhaps in different sections? I think its really important for users (and developers) to understand - through UX and otherwise - that MOWs/Marketplace represent expanded content options rather than a "dilution" of the app store experience.  Also keen to see the UX for what's surfaced when a user does a specific keyword search as well! +1 to flekkowich's comment on creating use cases - was already thinking this. Happy to collaborate.

**Comment by ezoehunt** [comment]
Thanks Rina and Sakina. We're working to fill out the project site with the "reasons" behind design decisions. These will include flows, diagrams, etc dealing with the use cases you've described (and others). Will work with both of you on that.

Re: messaging in general - we have many thoughts about that. Marketplace does not currently have a POV. It needs one. So we'll work with you both on that.

Thanks again. Great ideas.

**Comment by devaneymoz** [comment]
I'm a bit torn on how much we should display apps v. websites as distinct forms of content (in a design layout sense), or how much their lines are blurred within Marketplace. In reviewing the wireframes, I sorta like the slight distinction in the UI (e.g. 'Get' v. 'Open'). I see this slight distinction being a benefit in terms of say, news or entertainment apps, where we might have an ESPN app next to a Sports Illustrated MOW, and the user likely doesn't care about the 

As for illustrating a consumer-facing Marketplace POV (e.g. 'About' page, FAQ, or other messaging elements to that effect), that falls within my purview, so I'll be happy to reignite that effort (which Niran and I worked on maybe a year ago before other priorities derailed it; I don't think much of that messaging is relevant today since it predated desktop apps and MOW).

**Comment by punchyfrisky** [comment]
Agree we need a POV and would love to be part of this.

*Sakina Groth  *
Phone: 850.418.3825
Email: sgroth@mozilla.com
IRC: sakinagroth http://www.mozilla.org/
https://twitter.com/SakinaGroth
https://newoldstamp.com/editor/www.linkedin.com/in/sakinagroth/

**Comment by ezoehunt** [comment]
Just created a new issue for POV. Sakina, Rina, Scott, and Niran to work it out!

**Comment by eviljeff** [comment]
What's the use case for a user having private website submissions? - isn't the point of them is to share the website with other people, (otherwise its the same as my websites)?

**Comment by eviljeff** [comment]
Where do you envision 'my submissions' sitting in terms of front-end UX & infrastructure vs. devhub UX & infrastructure?  It seems to sit more with app submissions on devhub - though this could be the start of moving app submission pages to a modern setup too I suppose.

**Comment by ezoehunt** [comment]
Good questions.
Re; private website submissions. The submission is always public. The attribution can be public or private. So a website is submitted and appears publicly in MP. User has a choice (at acct level, not per site level) to either show his name/photo on the website detail page, or not to show those. Will clarify in the reqs. 
The MP and Review teams are working through the details of the "submission process." I agree that the functionality is similar to submitting an app, and that Devhub could be the place to do that in the future. Other thoughts are a "more friendly" format like a SurveyGizmo form. If you're interested in this process, you might reach out to Lisa B. Otherwise stay tuned for details!

**Comment by eviljeff** [comment]
Rather than the process, I was referring to the 'My Submissions' page mocked up (http://marketplaceux.github.io/mow/strategy/figures/figure_my_subs.png) compared to https://marketplace.firefox.com/developers/submissions (also called 'My Submissions', incidentally)
