### ISSUE TITLE
Determine "popularity" of websites

### ISSUE THREAD

**Issue by ezoehunt** [MarketplaceUX/mow#7]
@dbialer suggested we need to figure out how popularity works for websites. He'll drive this forward. @robhudson and @mat are interested and have ideas.

Some of the issues involved:
1. When launched, websites won't have popularity, so they would be at the bottom of the Popular page.
2. Content types won't share the same kind of popularity. So if we rank them all using the same scale, some content types will always be lower than others. E.g., ringtones may not be used as much, so even if they're super popular for ringtones, they won't get to the top of Popular.

From UX perspective: the ideal scenario is that Popular represents a mix of items from all content types.

**Idea:** Popular right now is a ranked list of all apps, so theoretically you could just keep loading more and get to the bottom of the list. Perhaps instead we choose a number, say, 30-50. We divide that number by the number of content types, so 30/2 (apps + websites) = 15. And we grab the top 15 popular apps and website and mix them together.

**Comment by robhudson** [comment]
Just throwing this in here... The top hits aggregation could possibly be used to get the top X pieces of content by some sorting field (e.g. popularity) bucketed into content types (app, website, etc) in a single ES query.

http://www.elastic.co/guide/en/elasticsearch/reference/1.x/search-aggregations-metrics-top-hits-aggregation.html

To support something like this we would probably need to add a `content_type` column that we can facet on. I'm not sure if the ES document type is available to aggregations to do this.

So if we need that, it's there. But we may find some other solution as well. I'd be concerned about using this too much across the site since it is an aggregation and probably more expensive than a straight up search query.
